name: Special_Reservation
version: 1.1.0
main: io.github.emckee10.specialreservation.SR
description: Reserves spots on a server for 'special' users
author: TheITx
commands:
  reserve:
    description: Change the number of reserved slots.
    permission: special_reservation.reserve
    permission-message: You do not have the permission to use this command.
    usage: "&cUsage: /<command> [Integer of reserved slots for the server]"
  rstoggle:
    description: Toggles reserved slots
    permission: special_reservation.rstoggle
    permission-message: You do not have the permission to use this command.
    usage: "&cIncorrect command usage, try /ReserveSlotsToggle <true/false>."
  SpecialFullMessage:
    description: Changes special full message, use & for colors
    aliases: SMessage
    permission: special_reservation.changeFullMessage
    permission-message: You do not have the permission to use this command.
    usage: "Usage: /<command> [message you would like to display]"
  RegularFullMessage:
    description: Changes regular full message, use & for colors
    aliases: RMessage
    permission: special_reservation.changeFullMessage
    permission-message: You do not have the permission to use this command.
    usage: "Usage: /<command> [message you would like to display]"
  SpecialOnline:
    description: Gives you the names and a count of all players with special bypass
    permission: special_reservation.showonline
    permission-message: You do not have the permission to use this command.
    usage: "Usage: /<command>."
  StaffOnline:
    description: Gives you the names and a count of all players with staff bypass
    permission: special_reservation.showonline
    permission-message: You do not have the permission to use this command.
    usage: "Usage: /<command>."
  RegularOnline:
    description: Gives you the names and a count of all players with no bypasses
    permission: special_reservation.showonline
    permission-message: You do not have the permission to use this command.
    usage: "Usage: /<command>."
  ReloadSR:
    description: Reloads the plugin with the correct number of players with specific permissions.
    permission: special_reservation.reloadsr
    permission-message: You do not have the permission to use this command.
    usage: "Usage: /<command>."
    #giveStaffSlotsPermission:
    #description: Gives a player staff permission. (always limit override)
    #aliases: StaffSlotsPerm
    #permission: special_reservation.staffslotsperm
    #permission-message: You do not have the permission to use this command.
    #usage: "Usage: /<command> [player name]"
    #giveSpecialSlotsPermission:
    #description: Gives a player special permission. (access to reserved slots)
    #aliases: SpecialSlotsPerm
    #permission: special_reservation.specialslotsperm
    #permission-message: You do not have the permission to use this command.
    #usage: "Usage: /<command> [player name]"
permissions:
  special_reservation.specialbypass:
    description: permission to allow a user into the reserved slots
  special_reservation.staffbypass:
    description: permission to allow staff to bypass server slot limit
  special_reservation.showonline:
    description: permission to check players with staff bypass online
    default: op
  special_reservation.reserve:
    description: permission for changing number of reserved slots
    default: op
  special_reservation.rstoggle:
    description: permission for toggling reserved slots
    default: op
  special_reservation.changeFullMessage:
    description: permission to change Full Messages
    default: op
  special_reservation.reloadsr:
    default: op
    # special_reservation.staffslotsperm:
    #description: permission to give staff slot access (always limit override)
    # special_reservation.specialslotsperm:
    #description: permission to give special slot access (access to reserved slots)
